services:
    mongoserver:
        image: mongo
        container_name: mongodb-server
        environment:
           - MONGO_INITDB_ROOT_USERNAME: root
           - MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
           - ~/mongo/data:/data/db
        networks:
           - findroomie-network
    backendapi:
        image: muhammedanaskhan/findroomie-backend:v2
        container_name: findroomie-backend-server
        ports:
           - "5513:5513"
        networks:
            - findroomie-network
        env_file: .env
        depends_on:
            - mongoserver
        
networks:
    findroomie-network:
        driver: bridge